### ISSUE TITLE
Handle inverted media queries

### ISSUE THREAD

**Issue by vis97c** [OlehDutchenko/sort-css-media-queries#30]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries#inverting_a_querys_meaning) we can define a media queries and invert its behavior (negation). Its already widely supported.

Right now the sorter does not support said feature. I'm already working on a proposal but I'm trying to think of the approach.

**Comment by OlehDutchenko** [comment]
Hi, Victor!
You can submit your proposals and implementations for consideration
