### ISSUE TITLE
Alternative to mqpacker

### ISSUE THREAD

**Issue by jonnitto** [OlehDutchenko/sort-css-media-queries#4]
I don't know why, but https://github.com/hail2u/node-css-mqpacker is deprecated. Do you have an alternative?

**Comment by yunusga** [comment]
@jonnitto [postcss-sort-media-queries](https://github.com/solversgroup/postcss-sort-media-queries)

**Comment by OlehDutchenko** [comment]
Great solution! Added to the `Readme` as an offer for people looking for options.
